### ISSUE TITLE
Failing this test case

### ISSUE THREAD

**Issue by EonYang** [LucaCappelletti94/dict_hash#3]
## Version:
```
dict-hash==1.1.14
python==3.7.9
```

## Test Case
```
from dict_hash import sha256

d1 = {
    'tune_best_model': True,
    'target': 'def'
}

d2 = {
    'target': 'def',
    'tune_best_model': True
}

h1, h2 = sha256(d1), sha256(d2)

assert h1 == h2, f'{h1} != {h2}'

```
## Output:
```
AssertionError: 0eb22ae4f46a2d9529d841fc905e1dc0cd07782ccda4a834d556c2eb5e2b8c58 != 80e801aadf2453bb0c49d0f2667f1e612092464cb9d7dca071dd7c3ffdf86475
```

## Expected Output
`Assert True`

## Possible Solution:

https://github.com/LucaCappelletti94/dict_hash/blob/b6e22a17fd79d1a08cbfe81f1c8c7abc026ab9f6/dict_hash/dict_hash.py#L127

change from ` return json.dumps(deflate(_convert(dictionary), leave_tuples=True))`
to ` return json.dumps(deflate(_convert(dictionary), leave_tuples=True), sort_keys=True)`

However, maybe it's not a good idea because it would make the time complexity O(NlogN).

**Comment by LucaCappelletti94** [comment]
Hello @EonYang, I was under the impression that the `json.dumps` also sorted the keys. I will definitely be fixing that and I'll run a sort-of benchmark to understand how that changes things.

Thank you!

**Comment by LucaCappelletti94** [comment]
The measured difference is not statistically significant. Feature added in!

**Comment by LucaCappelletti94** [comment]
The new version is now available from Pypi. Do let me know if everything works as expected.

**Comment by EonYang** [comment]
Great!

Thank you so much for offering this awesome package!

**Comment by LucaCappelletti94** [comment]
Thanks! This package was designed as a module of the [cache decorator](https://github.com/zommiommy/cache_decorator) package. It may save you some time if you are using it for a similar goal.

**Comment by EonYang** [comment]
Yeah, that's exactly what I'm doing, lol.

Alright, I tested the new release `1.1.15` and can confirm that this issue is no more.

Thank you and have a nice coding.
