### ISSUE TITLE
Python datetime & date fields support

### ISSUE THREAD

**Issue by vlaskinvlad** [LucaCappelletti94/dict_hash#4]
I was trying to use the library, but endned up scripting my own because of the absense of the datetimefields support out of the box.

Something like that might do:

```python
if isinstance(value, (date, datetime)): 
    value_to_use = value.isoformat()
```

**Comment by LucaCappelletti94** [comment]
On it!

**Comment by LucaCappelletti94** [comment]
Can you think of other objects that were not currently covered? May I ask what is your use case? We use the library mostly for cache-related stuff here: https://github.com/zommiommy/cache_decorator

**Comment by Matthias1590** [comment]
I created a pull request that covers datetime objects #5

**Comment by LucaCappelletti94** [comment]
Looking into it, thanks @Matthias1590 !

**Comment by LucaCappelletti94** [comment]
I have published the new version on Pypi. Do let me know if it works fine for you guys!

**Comment by Matthias1590** [comment]
Works for me! Including datetime.datetime is not necessary though.

**Comment by LucaCappelletti94** [comment]
I'll remove it, you are right.
