### ISSUE TITLE
MAC address object of class EUI('00-1B-77-49-54-FD') are not supported

### ISSUE THREAD

**Issue by lkpatel** [LucaCappelletti94/dict_hash#8]
Hashing of objects of class EUI have failed with following error-

NotImplementedError: Object of class EUI not currently supported

Could you please implement it ?

Regards

**Comment by LucaCappelletti94** [comment]
Ehm, what object is that? From what package? What code reproduces the error?

**Comment by lkpatel** [comment]
The object MAC(Media Access control) address from **netaddr** python package (https://netaddr.readthedocs.io). In my use case, I want to keep a hash to ensure that MAC addresses have not been changed in a device. Following code will produce the error. 
```
from netaddr import *
from dict_hash import sha256
mac_list = [EUI ('00-1B-77-49-54-FD')]
print(sha256(mac_list))
```
Regards

**Comment by LucaCappelletti94** [comment]
I have added support for recursively hashable objects, which should include most objects such as `EUI`.
Please do let me know if the latest version I published on PyPI fits the bill for you.

Consider starring the repository and [support its development](https://github.com/sponsors/LucaCappelletti94) if you found this useful and saved you time :)
